// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsmheerdjsmbdgdhfhys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zbWhlZXJkanNtYmRnZGhmaHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5OTM1MTgsImV4cCI6MjA2MjU2OTUxOH0.IkOOEJNxQx5OvrG3B11fZxkAOC2C-zoWlZRcdX5Yqc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);