// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://elizkeyziqbqkuqhcvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsaXprZXl6aXFicWt1cWhjdnEiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTczNzU3ODYwOCwiZXhwIjoyMDUzMTU0NjA4fQ.v5d2g8YoT5O5OTXWl_6GNzd-8NfLR0NF6d6c1cBlA2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);